document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("  <head>");
document.writeln("    <meta charset=\'UTF-8\' />");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\' />");
document.writeln("    <title>分离式导航</title>");
document.writeln("    <style>");
document.writeln("      .main-nav {");
document.writeln("        display: flex;");
document.writeln("      }");
document.writeln("      .main-nav li{");
document.writeln("        margin-right: 10px;");
document.writeln("        list-style: none;");
document.writeln("      }");
document.writeln("      .push {");
document.writeln("        margin-right: 0;");
document.writeln("        margin-left: auto;");
document.writeln("      }");
document.writeln("    </style>");
document.writeln("  </head>");
document.writeln("  <body>");
document.writeln("    <p>一种导航样式，其中一个或多个元素与其余导航项之间是分离的。</p>");
document.writeln("    <p>一种常见的导航样式是将一个元素推离其他元素。我们可以使用弹性盒（Flexbox）实现这一点，而不需要将两组项目放入两个单独的弹性容器（flex container）中。</p>");
document.writeln("    <nav>");
document.writeln("      <ul class=\'main-nav\'>");
document.writeln("        <li><a href=\'\'>首页</a></li>");
document.writeln("        <li><a href=\'\'>产品</a></li>");
document.writeln("        <li><a href=\'\'>关于</a></li>");
document.writeln("        <li><a href=\'\'>联系我们</a></li>");
document.writeln("        <li class=\'push\'><a href=\'\'>个人中心</a></li>");
document.writeln("      </ul>");
document.writeln("    </nav>");
document.writeln("  </body>");
document.writeln("</html>");
document.writeln("");